"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from mix_python_sdk.errors import MixError
from mix_python_sdk.models import resterror as models_resterror
from mix_python_sdk.types import BaseModel
from typing import Optional


class ErrorResponseData(BaseModel):
    error: models_resterror.RESTError


@dataclass(frozen=True)
class ErrorResponse(MixError):
    data: ErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: ErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
