"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .cancelsessionprocessingop import (
        CancelSessionProcessingData,
        CancelSessionProcessingDataTypedDict,
        CancelSessionProcessingRequest,
        CancelSessionProcessingRequestTypedDict,
        CancelSessionProcessingResponse,
        CancelSessionProcessingResponseTypedDict,
    )
    from .createsessionop import (
        CreateSessionRequest,
        CreateSessionRequestTypedDict,
        CreateSessionResponse,
        CreateSessionResponseTypedDict,
    )
    from .deletesessionop import DeleteSessionRequest, DeleteSessionRequestTypedDict
    from .denypermissionop import (
        DenyPermissionData,
        DenyPermissionDataTypedDict,
        DenyPermissionRequest,
        DenyPermissionRequestTypedDict,
        DenyPermissionResponse,
        DenyPermissionResponseTypedDict,
    )
    from .forksessionop import (
        ForkSessionRequest,
        ForkSessionRequestBody,
        ForkSessionRequestBodyTypedDict,
        ForkSessionRequestTypedDict,
        ForkSessionResponse,
        ForkSessionResponseTypedDict,
    )
    from .getcommandop import (
        GetCommandData,
        GetCommandDataTypedDict,
        GetCommandRequest,
        GetCommandRequestTypedDict,
        GetCommandResponse,
        GetCommandResponseTypedDict,
    )
    from .getmessagehistoryop import (
        GetMessageHistoryRequest,
        GetMessageHistoryRequestTypedDict,
        GetMessageHistoryResponse,
        GetMessageHistoryResponseTypedDict,
    )
    from .getsessionmessagesop import (
        GetSessionMessagesRequest,
        GetSessionMessagesRequestTypedDict,
        GetSessionMessagesResponse,
        GetSessionMessagesResponseTypedDict,
    )
    from .getsessionop import (
        GetSessionRequest,
        GetSessionRequestTypedDict,
        GetSessionResponse,
        GetSessionResponseTypedDict,
    )
    from .grantpermissionop import (
        GrantPermissionData,
        GrantPermissionDataTypedDict,
        GrantPermissionRequest,
        GrantPermissionRequestTypedDict,
        GrantPermissionResponse,
        GrantPermissionResponseTypedDict,
    )
    from .healthcheckop import (
        HealthCheckData,
        HealthCheckDataTypedDict,
        HealthCheckResponse,
        HealthCheckResponseTypedDict,
    )
    from .initiateoauthloginop import (
        InitiateOAuthLoginData,
        InitiateOAuthLoginDataTypedDict,
        InitiateOAuthLoginResponse,
        InitiateOAuthLoginResponseTypedDict,
    )
    from .listcommandsop import (
        ListCommandsData,
        ListCommandsDataTypedDict,
        ListCommandsResponse,
        ListCommandsResponseTypedDict,
    )
    from .listmcpserversop import (
        ListMcpServersData,
        ListMcpServersDataTypedDict,
        ListMcpServersResponse,
        ListMcpServersResponseTypedDict,
        Tool,
        ToolTypedDict,
    )
    from .listsessionsop import ListSessionsResponse, ListSessionsResponseTypedDict
    from .messagedata import MessageData, MessageDataTypedDict
    from .messagerole import MessageRole
    from .resterror import RESTError, RESTErrorTypedDict, Type
    from .sendmessageop import (
        SendMessageRequest,
        SendMessageRequestBody,
        SendMessageRequestBodyTypedDict,
        SendMessageRequestTypedDict,
        SendMessageResponse,
        SendMessageResponseTypedDict,
    )
    from .sessiondata import SessionData, SessionDataTypedDict
    from .setapikeyop import (
        SetAPIKeyData,
        SetAPIKeyDataTypedDict,
        SetAPIKeyRequest,
        SetAPIKeyRequestTypedDict,
        SetAPIKeyResponse,
        SetAPIKeyResponseTypedDict,
    )
    from .toolcalldata import ToolCallData, ToolCallDataTypedDict

__all__ = [
    "CancelSessionProcessingData",
    "CancelSessionProcessingDataTypedDict",
    "CancelSessionProcessingRequest",
    "CancelSessionProcessingRequestTypedDict",
    "CancelSessionProcessingResponse",
    "CancelSessionProcessingResponseTypedDict",
    "CreateSessionRequest",
    "CreateSessionRequestTypedDict",
    "CreateSessionResponse",
    "CreateSessionResponseTypedDict",
    "DeleteSessionRequest",
    "DeleteSessionRequestTypedDict",
    "DenyPermissionData",
    "DenyPermissionDataTypedDict",
    "DenyPermissionRequest",
    "DenyPermissionRequestTypedDict",
    "DenyPermissionResponse",
    "DenyPermissionResponseTypedDict",
    "ForkSessionRequest",
    "ForkSessionRequestBody",
    "ForkSessionRequestBodyTypedDict",
    "ForkSessionRequestTypedDict",
    "ForkSessionResponse",
    "ForkSessionResponseTypedDict",
    "GetCommandData",
    "GetCommandDataTypedDict",
    "GetCommandRequest",
    "GetCommandRequestTypedDict",
    "GetCommandResponse",
    "GetCommandResponseTypedDict",
    "GetMessageHistoryRequest",
    "GetMessageHistoryRequestTypedDict",
    "GetMessageHistoryResponse",
    "GetMessageHistoryResponseTypedDict",
    "GetSessionMessagesRequest",
    "GetSessionMessagesRequestTypedDict",
    "GetSessionMessagesResponse",
    "GetSessionMessagesResponseTypedDict",
    "GetSessionRequest",
    "GetSessionRequestTypedDict",
    "GetSessionResponse",
    "GetSessionResponseTypedDict",
    "GrantPermissionData",
    "GrantPermissionDataTypedDict",
    "GrantPermissionRequest",
    "GrantPermissionRequestTypedDict",
    "GrantPermissionResponse",
    "GrantPermissionResponseTypedDict",
    "HealthCheckData",
    "HealthCheckDataTypedDict",
    "HealthCheckResponse",
    "HealthCheckResponseTypedDict",
    "InitiateOAuthLoginData",
    "InitiateOAuthLoginDataTypedDict",
    "InitiateOAuthLoginResponse",
    "InitiateOAuthLoginResponseTypedDict",
    "ListCommandsData",
    "ListCommandsDataTypedDict",
    "ListCommandsResponse",
    "ListCommandsResponseTypedDict",
    "ListMcpServersData",
    "ListMcpServersDataTypedDict",
    "ListMcpServersResponse",
    "ListMcpServersResponseTypedDict",
    "ListSessionsResponse",
    "ListSessionsResponseTypedDict",
    "MessageData",
    "MessageDataTypedDict",
    "MessageRole",
    "RESTError",
    "RESTErrorTypedDict",
    "SendMessageRequest",
    "SendMessageRequestBody",
    "SendMessageRequestBodyTypedDict",
    "SendMessageRequestTypedDict",
    "SendMessageResponse",
    "SendMessageResponseTypedDict",
    "SessionData",
    "SessionDataTypedDict",
    "SetAPIKeyData",
    "SetAPIKeyDataTypedDict",
    "SetAPIKeyRequest",
    "SetAPIKeyRequestTypedDict",
    "SetAPIKeyResponse",
    "SetAPIKeyResponseTypedDict",
    "Tool",
    "ToolCallData",
    "ToolCallDataTypedDict",
    "ToolTypedDict",
    "Type",
]

_dynamic_imports: dict[str, str] = {
    "CancelSessionProcessingData": ".cancelsessionprocessingop",
    "CancelSessionProcessingDataTypedDict": ".cancelsessionprocessingop",
    "CancelSessionProcessingRequest": ".cancelsessionprocessingop",
    "CancelSessionProcessingRequestTypedDict": ".cancelsessionprocessingop",
    "CancelSessionProcessingResponse": ".cancelsessionprocessingop",
    "CancelSessionProcessingResponseTypedDict": ".cancelsessionprocessingop",
    "CreateSessionRequest": ".createsessionop",
    "CreateSessionRequestTypedDict": ".createsessionop",
    "CreateSessionResponse": ".createsessionop",
    "CreateSessionResponseTypedDict": ".createsessionop",
    "DeleteSessionRequest": ".deletesessionop",
    "DeleteSessionRequestTypedDict": ".deletesessionop",
    "DenyPermissionData": ".denypermissionop",
    "DenyPermissionDataTypedDict": ".denypermissionop",
    "DenyPermissionRequest": ".denypermissionop",
    "DenyPermissionRequestTypedDict": ".denypermissionop",
    "DenyPermissionResponse": ".denypermissionop",
    "DenyPermissionResponseTypedDict": ".denypermissionop",
    "ForkSessionRequest": ".forksessionop",
    "ForkSessionRequestBody": ".forksessionop",
    "ForkSessionRequestBodyTypedDict": ".forksessionop",
    "ForkSessionRequestTypedDict": ".forksessionop",
    "ForkSessionResponse": ".forksessionop",
    "ForkSessionResponseTypedDict": ".forksessionop",
    "GetCommandData": ".getcommandop",
    "GetCommandDataTypedDict": ".getcommandop",
    "GetCommandRequest": ".getcommandop",
    "GetCommandRequestTypedDict": ".getcommandop",
    "GetCommandResponse": ".getcommandop",
    "GetCommandResponseTypedDict": ".getcommandop",
    "GetMessageHistoryRequest": ".getmessagehistoryop",
    "GetMessageHistoryRequestTypedDict": ".getmessagehistoryop",
    "GetMessageHistoryResponse": ".getmessagehistoryop",
    "GetMessageHistoryResponseTypedDict": ".getmessagehistoryop",
    "GetSessionMessagesRequest": ".getsessionmessagesop",
    "GetSessionMessagesRequestTypedDict": ".getsessionmessagesop",
    "GetSessionMessagesResponse": ".getsessionmessagesop",
    "GetSessionMessagesResponseTypedDict": ".getsessionmessagesop",
    "GetSessionRequest": ".getsessionop",
    "GetSessionRequestTypedDict": ".getsessionop",
    "GetSessionResponse": ".getsessionop",
    "GetSessionResponseTypedDict": ".getsessionop",
    "GrantPermissionData": ".grantpermissionop",
    "GrantPermissionDataTypedDict": ".grantpermissionop",
    "GrantPermissionRequest": ".grantpermissionop",
    "GrantPermissionRequestTypedDict": ".grantpermissionop",
    "GrantPermissionResponse": ".grantpermissionop",
    "GrantPermissionResponseTypedDict": ".grantpermissionop",
    "HealthCheckData": ".healthcheckop",
    "HealthCheckDataTypedDict": ".healthcheckop",
    "HealthCheckResponse": ".healthcheckop",
    "HealthCheckResponseTypedDict": ".healthcheckop",
    "InitiateOAuthLoginData": ".initiateoauthloginop",
    "InitiateOAuthLoginDataTypedDict": ".initiateoauthloginop",
    "InitiateOAuthLoginResponse": ".initiateoauthloginop",
    "InitiateOAuthLoginResponseTypedDict": ".initiateoauthloginop",
    "ListCommandsData": ".listcommandsop",
    "ListCommandsDataTypedDict": ".listcommandsop",
    "ListCommandsResponse": ".listcommandsop",
    "ListCommandsResponseTypedDict": ".listcommandsop",
    "ListMcpServersData": ".listmcpserversop",
    "ListMcpServersDataTypedDict": ".listmcpserversop",
    "ListMcpServersResponse": ".listmcpserversop",
    "ListMcpServersResponseTypedDict": ".listmcpserversop",
    "Tool": ".listmcpserversop",
    "ToolTypedDict": ".listmcpserversop",
    "ListSessionsResponse": ".listsessionsop",
    "ListSessionsResponseTypedDict": ".listsessionsop",
    "MessageData": ".messagedata",
    "MessageDataTypedDict": ".messagedata",
    "MessageRole": ".messagerole",
    "RESTError": ".resterror",
    "RESTErrorTypedDict": ".resterror",
    "Type": ".resterror",
    "SendMessageRequest": ".sendmessageop",
    "SendMessageRequestBody": ".sendmessageop",
    "SendMessageRequestBodyTypedDict": ".sendmessageop",
    "SendMessageRequestTypedDict": ".sendmessageop",
    "SendMessageResponse": ".sendmessageop",
    "SendMessageResponseTypedDict": ".sendmessageop",
    "SessionData": ".sessiondata",
    "SessionDataTypedDict": ".sessiondata",
    "SetAPIKeyData": ".setapikeyop",
    "SetAPIKeyDataTypedDict": ".setapikeyop",
    "SetAPIKeyRequest": ".setapikeyop",
    "SetAPIKeyRequestTypedDict": ".setapikeyop",
    "SetAPIKeyResponse": ".setapikeyop",
    "SetAPIKeyResponseTypedDict": ".setapikeyop",
    "ToolCallData": ".toolcalldata",
    "ToolCallDataTypedDict": ".toolcalldata",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
