"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .cancelsessionprocessingop import (
        CancelSessionProcessingRequest,
        CancelSessionProcessingRequestTypedDict,
        CancelSessionProcessingResponse,
        CancelSessionProcessingResponseTypedDict,
    )
    from .createsessionop import CreateSessionRequest, CreateSessionRequestTypedDict
    from .deletecredentialsop import (
        DeleteCredentialsRequest,
        DeleteCredentialsRequestTypedDict,
        DeleteCredentialsResponse,
        DeleteCredentialsResponseTypedDict,
    )
    from .deletesessionfileop import (
        DeleteSessionFileRequest,
        DeleteSessionFileRequestTypedDict,
    )
    from .deletesessionop import DeleteSessionRequest, DeleteSessionRequestTypedDict
    from .denypermissionop import (
        DenyPermissionRequest,
        DenyPermissionRequestTypedDict,
        DenyPermissionResponse,
        DenyPermissionResponseTypedDict,
    )
    from .fileinfo import FileInfo, FileInfoTypedDict
    from .forksessionop import (
        ForkSessionRequest,
        ForkSessionRequestBody,
        ForkSessionRequestBodyTypedDict,
        ForkSessionRequestTypedDict,
    )
    from .getauthstatusop import (
        GetAuthStatusAuthMethod,
        GetAuthStatusResponse,
        GetAuthStatusResponseTypedDict,
        Providers,
        ProvidersTypedDict,
    )
    from .getavailableprovidersop import (
        GetAvailableProvidersResponse,
        GetAvailableProvidersResponseTypedDict,
    )
    from .getcommandop import (
        GetCommandRequest,
        GetCommandRequestTypedDict,
        GetCommandResponse,
        GetCommandResponseTypedDict,
    )
    from .getmessagehistoryop import (
        GetMessageHistoryRequest,
        GetMessageHistoryRequestTypedDict,
    )
    from .getpreferencesop import (
        AvailableProviders,
        AvailableProvidersTypedDict,
        GetPreferencesPreferences,
        GetPreferencesPreferencesTypedDict,
        GetPreferencesResponse,
        GetPreferencesResponseTypedDict,
    )
    from .getsessionfileop import (
        GetSessionFileRequest,
        GetSessionFileRequestTypedDict,
        GetSessionFileResponse,
        GetSessionFileResponseTypedDict,
    )
    from .getsessionmessagesop import (
        GetSessionMessagesRequest,
        GetSessionMessagesRequestTypedDict,
    )
    from .getsessionop import GetSessionRequest, GetSessionRequestTypedDict
    from .gettoolsstatusop import (
        Categories,
        CategoriesTypedDict,
        GetToolsStatusResponse,
        GetToolsStatusResponseTypedDict,
        GetToolsStatusTool,
        GetToolsStatusToolTypedDict,
    )
    from .grantpermissionop import (
        GrantPermissionRequest,
        GrantPermissionRequestTypedDict,
        GrantPermissionResponse,
        GrantPermissionResponseTypedDict,
    )
    from .handleoauthcallbackop import (
        HandleOAuthCallbackRequest,
        HandleOAuthCallbackRequestTypedDict,
        HandleOAuthCallbackResponse,
        HandleOAuthCallbackResponseTypedDict,
    )
    from .healthcheckop import HealthCheckResponse, HealthCheckResponseTypedDict
    from .initiateoauthloginop import (
        InitiateOAuthLoginResponse,
        InitiateOAuthLoginResponseTypedDict,
    )
    from .listcommandsop import ListCommandsResponse, ListCommandsResponseTypedDict
    from .listmcpserversop import (
        ListMcpServersResponse,
        ListMcpServersResponseTypedDict,
        ListMcpServersTool,
        ListMcpServersToolTypedDict,
    )
    from .listsessionfilesop import (
        ListSessionFilesRequest,
        ListSessionFilesRequestTypedDict,
    )
    from .messagedata import MessageData, MessageDataTypedDict
    from .messagerole import MessageRole
    from .resetpreferencesop import (
        ResetPreferencesResponse,
        ResetPreferencesResponseTypedDict,
    )
    from .resterror import RESTError, RESTErrorTypedDict, Type
    from .sendmessageop import (
        SendMessageRequest,
        SendMessageRequestBody,
        SendMessageRequestBodyTypedDict,
        SendMessageRequestTypedDict,
    )
    from .sessiondata import SessionData, SessionDataTypedDict
    from .setapikeyop import (
        SetAPIKeyRequest,
        SetAPIKeyRequestTypedDict,
        SetAPIKeyResponse,
        SetAPIKeyResponseTypedDict,
    )
    from .startoauthflowop import (
        StartOAuthFlowRequest,
        StartOAuthFlowRequestTypedDict,
        StartOAuthFlowResponse,
        StartOAuthFlowResponseTypedDict,
    )
    from .storeapikeyop import (
        Provider,
        StoreAPIKeyRequest,
        StoreAPIKeyRequestTypedDict,
        StoreAPIKeyResponse,
        StoreAPIKeyResponseTypedDict,
    )
    from .toolcalldata import ToolCallData, ToolCallDataTypedDict
    from .updatepreferencesop import (
        UpdatePreferencesRequest,
        UpdatePreferencesRequestTypedDict,
        UpdatePreferencesResponse,
        UpdatePreferencesResponseTypedDict,
    )
    from .uploadsessionfileop import (
        File,
        FileTypedDict,
        UploadSessionFileRequest,
        UploadSessionFileRequestBody,
        UploadSessionFileRequestBodyTypedDict,
        UploadSessionFileRequestTypedDict,
    )
    from .validatepreferredproviderop import (
        ValidatePreferredProviderAuthMethod,
        ValidatePreferredProviderResponse,
        ValidatePreferredProviderResponseTypedDict,
    )

__all__ = [
    "AvailableProviders",
    "AvailableProvidersTypedDict",
    "CancelSessionProcessingRequest",
    "CancelSessionProcessingRequestTypedDict",
    "CancelSessionProcessingResponse",
    "CancelSessionProcessingResponseTypedDict",
    "Categories",
    "CategoriesTypedDict",
    "CreateSessionRequest",
    "CreateSessionRequestTypedDict",
    "DeleteCredentialsRequest",
    "DeleteCredentialsRequestTypedDict",
    "DeleteCredentialsResponse",
    "DeleteCredentialsResponseTypedDict",
    "DeleteSessionFileRequest",
    "DeleteSessionFileRequestTypedDict",
    "DeleteSessionRequest",
    "DeleteSessionRequestTypedDict",
    "DenyPermissionRequest",
    "DenyPermissionRequestTypedDict",
    "DenyPermissionResponse",
    "DenyPermissionResponseTypedDict",
    "File",
    "FileInfo",
    "FileInfoTypedDict",
    "FileTypedDict",
    "ForkSessionRequest",
    "ForkSessionRequestBody",
    "ForkSessionRequestBodyTypedDict",
    "ForkSessionRequestTypedDict",
    "GetAuthStatusAuthMethod",
    "GetAuthStatusResponse",
    "GetAuthStatusResponseTypedDict",
    "GetAvailableProvidersResponse",
    "GetAvailableProvidersResponseTypedDict",
    "GetCommandRequest",
    "GetCommandRequestTypedDict",
    "GetCommandResponse",
    "GetCommandResponseTypedDict",
    "GetMessageHistoryRequest",
    "GetMessageHistoryRequestTypedDict",
    "GetPreferencesPreferences",
    "GetPreferencesPreferencesTypedDict",
    "GetPreferencesResponse",
    "GetPreferencesResponseTypedDict",
    "GetSessionFileRequest",
    "GetSessionFileRequestTypedDict",
    "GetSessionFileResponse",
    "GetSessionFileResponseTypedDict",
    "GetSessionMessagesRequest",
    "GetSessionMessagesRequestTypedDict",
    "GetSessionRequest",
    "GetSessionRequestTypedDict",
    "GetToolsStatusResponse",
    "GetToolsStatusResponseTypedDict",
    "GetToolsStatusTool",
    "GetToolsStatusToolTypedDict",
    "GrantPermissionRequest",
    "GrantPermissionRequestTypedDict",
    "GrantPermissionResponse",
    "GrantPermissionResponseTypedDict",
    "HandleOAuthCallbackRequest",
    "HandleOAuthCallbackRequestTypedDict",
    "HandleOAuthCallbackResponse",
    "HandleOAuthCallbackResponseTypedDict",
    "HealthCheckResponse",
    "HealthCheckResponseTypedDict",
    "InitiateOAuthLoginResponse",
    "InitiateOAuthLoginResponseTypedDict",
    "ListCommandsResponse",
    "ListCommandsResponseTypedDict",
    "ListMcpServersResponse",
    "ListMcpServersResponseTypedDict",
    "ListMcpServersTool",
    "ListMcpServersToolTypedDict",
    "ListSessionFilesRequest",
    "ListSessionFilesRequestTypedDict",
    "MessageData",
    "MessageDataTypedDict",
    "MessageRole",
    "Provider",
    "Providers",
    "ProvidersTypedDict",
    "RESTError",
    "RESTErrorTypedDict",
    "ResetPreferencesResponse",
    "ResetPreferencesResponseTypedDict",
    "SendMessageRequest",
    "SendMessageRequestBody",
    "SendMessageRequestBodyTypedDict",
    "SendMessageRequestTypedDict",
    "SessionData",
    "SessionDataTypedDict",
    "SetAPIKeyRequest",
    "SetAPIKeyRequestTypedDict",
    "SetAPIKeyResponse",
    "SetAPIKeyResponseTypedDict",
    "StartOAuthFlowRequest",
    "StartOAuthFlowRequestTypedDict",
    "StartOAuthFlowResponse",
    "StartOAuthFlowResponseTypedDict",
    "StoreAPIKeyRequest",
    "StoreAPIKeyRequestTypedDict",
    "StoreAPIKeyResponse",
    "StoreAPIKeyResponseTypedDict",
    "ToolCallData",
    "ToolCallDataTypedDict",
    "Type",
    "UpdatePreferencesRequest",
    "UpdatePreferencesRequestTypedDict",
    "UpdatePreferencesResponse",
    "UpdatePreferencesResponseTypedDict",
    "UploadSessionFileRequest",
    "UploadSessionFileRequestBody",
    "UploadSessionFileRequestBodyTypedDict",
    "UploadSessionFileRequestTypedDict",
    "ValidatePreferredProviderAuthMethod",
    "ValidatePreferredProviderResponse",
    "ValidatePreferredProviderResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "CancelSessionProcessingRequest": ".cancelsessionprocessingop",
    "CancelSessionProcessingRequestTypedDict": ".cancelsessionprocessingop",
    "CancelSessionProcessingResponse": ".cancelsessionprocessingop",
    "CancelSessionProcessingResponseTypedDict": ".cancelsessionprocessingop",
    "CreateSessionRequest": ".createsessionop",
    "CreateSessionRequestTypedDict": ".createsessionop",
    "DeleteCredentialsRequest": ".deletecredentialsop",
    "DeleteCredentialsRequestTypedDict": ".deletecredentialsop",
    "DeleteCredentialsResponse": ".deletecredentialsop",
    "DeleteCredentialsResponseTypedDict": ".deletecredentialsop",
    "DeleteSessionFileRequest": ".deletesessionfileop",
    "DeleteSessionFileRequestTypedDict": ".deletesessionfileop",
    "DeleteSessionRequest": ".deletesessionop",
    "DeleteSessionRequestTypedDict": ".deletesessionop",
    "DenyPermissionRequest": ".denypermissionop",
    "DenyPermissionRequestTypedDict": ".denypermissionop",
    "DenyPermissionResponse": ".denypermissionop",
    "DenyPermissionResponseTypedDict": ".denypermissionop",
    "FileInfo": ".fileinfo",
    "FileInfoTypedDict": ".fileinfo",
    "ForkSessionRequest": ".forksessionop",
    "ForkSessionRequestBody": ".forksessionop",
    "ForkSessionRequestBodyTypedDict": ".forksessionop",
    "ForkSessionRequestTypedDict": ".forksessionop",
    "GetAuthStatusAuthMethod": ".getauthstatusop",
    "GetAuthStatusResponse": ".getauthstatusop",
    "GetAuthStatusResponseTypedDict": ".getauthstatusop",
    "Providers": ".getauthstatusop",
    "ProvidersTypedDict": ".getauthstatusop",
    "GetAvailableProvidersResponse": ".getavailableprovidersop",
    "GetAvailableProvidersResponseTypedDict": ".getavailableprovidersop",
    "GetCommandRequest": ".getcommandop",
    "GetCommandRequestTypedDict": ".getcommandop",
    "GetCommandResponse": ".getcommandop",
    "GetCommandResponseTypedDict": ".getcommandop",
    "GetMessageHistoryRequest": ".getmessagehistoryop",
    "GetMessageHistoryRequestTypedDict": ".getmessagehistoryop",
    "AvailableProviders": ".getpreferencesop",
    "AvailableProvidersTypedDict": ".getpreferencesop",
    "GetPreferencesPreferences": ".getpreferencesop",
    "GetPreferencesPreferencesTypedDict": ".getpreferencesop",
    "GetPreferencesResponse": ".getpreferencesop",
    "GetPreferencesResponseTypedDict": ".getpreferencesop",
    "GetSessionFileRequest": ".getsessionfileop",
    "GetSessionFileRequestTypedDict": ".getsessionfileop",
    "GetSessionFileResponse": ".getsessionfileop",
    "GetSessionFileResponseTypedDict": ".getsessionfileop",
    "GetSessionMessagesRequest": ".getsessionmessagesop",
    "GetSessionMessagesRequestTypedDict": ".getsessionmessagesop",
    "GetSessionRequest": ".getsessionop",
    "GetSessionRequestTypedDict": ".getsessionop",
    "Categories": ".gettoolsstatusop",
    "CategoriesTypedDict": ".gettoolsstatusop",
    "GetToolsStatusResponse": ".gettoolsstatusop",
    "GetToolsStatusResponseTypedDict": ".gettoolsstatusop",
    "GetToolsStatusTool": ".gettoolsstatusop",
    "GetToolsStatusToolTypedDict": ".gettoolsstatusop",
    "GrantPermissionRequest": ".grantpermissionop",
    "GrantPermissionRequestTypedDict": ".grantpermissionop",
    "GrantPermissionResponse": ".grantpermissionop",
    "GrantPermissionResponseTypedDict": ".grantpermissionop",
    "HandleOAuthCallbackRequest": ".handleoauthcallbackop",
    "HandleOAuthCallbackRequestTypedDict": ".handleoauthcallbackop",
    "HandleOAuthCallbackResponse": ".handleoauthcallbackop",
    "HandleOAuthCallbackResponseTypedDict": ".handleoauthcallbackop",
    "HealthCheckResponse": ".healthcheckop",
    "HealthCheckResponseTypedDict": ".healthcheckop",
    "InitiateOAuthLoginResponse": ".initiateoauthloginop",
    "InitiateOAuthLoginResponseTypedDict": ".initiateoauthloginop",
    "ListCommandsResponse": ".listcommandsop",
    "ListCommandsResponseTypedDict": ".listcommandsop",
    "ListMcpServersResponse": ".listmcpserversop",
    "ListMcpServersResponseTypedDict": ".listmcpserversop",
    "ListMcpServersTool": ".listmcpserversop",
    "ListMcpServersToolTypedDict": ".listmcpserversop",
    "ListSessionFilesRequest": ".listsessionfilesop",
    "ListSessionFilesRequestTypedDict": ".listsessionfilesop",
    "MessageData": ".messagedata",
    "MessageDataTypedDict": ".messagedata",
    "MessageRole": ".messagerole",
    "ResetPreferencesResponse": ".resetpreferencesop",
    "ResetPreferencesResponseTypedDict": ".resetpreferencesop",
    "RESTError": ".resterror",
    "RESTErrorTypedDict": ".resterror",
    "Type": ".resterror",
    "SendMessageRequest": ".sendmessageop",
    "SendMessageRequestBody": ".sendmessageop",
    "SendMessageRequestBodyTypedDict": ".sendmessageop",
    "SendMessageRequestTypedDict": ".sendmessageop",
    "SessionData": ".sessiondata",
    "SessionDataTypedDict": ".sessiondata",
    "SetAPIKeyRequest": ".setapikeyop",
    "SetAPIKeyRequestTypedDict": ".setapikeyop",
    "SetAPIKeyResponse": ".setapikeyop",
    "SetAPIKeyResponseTypedDict": ".setapikeyop",
    "StartOAuthFlowRequest": ".startoauthflowop",
    "StartOAuthFlowRequestTypedDict": ".startoauthflowop",
    "StartOAuthFlowResponse": ".startoauthflowop",
    "StartOAuthFlowResponseTypedDict": ".startoauthflowop",
    "Provider": ".storeapikeyop",
    "StoreAPIKeyRequest": ".storeapikeyop",
    "StoreAPIKeyRequestTypedDict": ".storeapikeyop",
    "StoreAPIKeyResponse": ".storeapikeyop",
    "StoreAPIKeyResponseTypedDict": ".storeapikeyop",
    "ToolCallData": ".toolcalldata",
    "ToolCallDataTypedDict": ".toolcalldata",
    "UpdatePreferencesRequest": ".updatepreferencesop",
    "UpdatePreferencesRequestTypedDict": ".updatepreferencesop",
    "UpdatePreferencesResponse": ".updatepreferencesop",
    "UpdatePreferencesResponseTypedDict": ".updatepreferencesop",
    "File": ".uploadsessionfileop",
    "FileTypedDict": ".uploadsessionfileop",
    "UploadSessionFileRequest": ".uploadsessionfileop",
    "UploadSessionFileRequestBody": ".uploadsessionfileop",
    "UploadSessionFileRequestBodyTypedDict": ".uploadsessionfileop",
    "UploadSessionFileRequestTypedDict": ".uploadsessionfileop",
    "ValidatePreferredProviderAuthMethod": ".validatepreferredproviderop",
    "ValidatePreferredProviderResponse": ".validatepreferredproviderop",
    "ValidatePreferredProviderResponseTypedDict": ".validatepreferredproviderop",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
