"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


CoreToolName = Literal[
    "Bash",
    "ReadText",
    "Glob",
    "ReadMedia",
    "Grep",
    "Write",
    "Edit",
    "python_execution",
    "Search",
    "TodoWrite",
    "ExitPlanMode",
    "ShowMedia",
    "Task",
]
r"""Core built-in tool names"""
