"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


CoreToolName = Literal[
    "bash",
    "ReadText",
    "glob",
    "ReadMedia",
    "grep",
    "write",
    "edit",
    "python_execution",
    "search",
    "todo_write",
    "exit_plan_mode",
    "show_media",
    "task",
]
r"""Core built-in tool names"""
