"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resterror import RESTError, RESTErrorTypedDict
from .sessiondata import SessionData, SessionDataTypedDict
from mix_python_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSessionRequestTypedDict(TypedDict):
    title: NotRequired[str]
    r"""Optional title for the session"""
    working_directory: NotRequired[str]
    r"""Optional working directory path"""


class CreateSessionRequest(BaseModel):
    title: Optional[str] = None
    r"""Optional title for the session"""

    working_directory: Annotated[
        Optional[str], pydantic.Field(alias="workingDirectory")
    ] = None
    r"""Optional working directory path"""


class CreateSessionResponseTypedDict(TypedDict):
    r"""Created session"""

    data: NotRequired[SessionDataTypedDict]
    error: NotRequired[RESTErrorTypedDict]
    message: NotRequired[str]
    r"""Optional message"""


class CreateSessionResponse(BaseModel):
    r"""Created session"""

    data: Optional[SessionData] = None

    error: Optional[RESTError] = None

    message: Optional[str] = None
    r"""Optional message"""
