"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteCredentialsRequestTypedDict(TypedDict):
    provider: str
    r"""Provider name (anthropic, openai, openrouter, gemini, brave)"""


class DeleteCredentialsRequest(BaseModel):
    provider: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Provider name (anthropic, openai, openrouter, gemini, brave)"""


class DeleteCredentialsResponseTypedDict(TypedDict):
    r"""Credentials deletion status"""

    message: NotRequired[str]
    r"""Status message"""
    provider: NotRequired[str]
    r"""Provider name"""
    status: NotRequired[str]
    r"""Operation status"""


class DeleteCredentialsResponse(BaseModel):
    r"""Credentials deletion status"""

    message: Optional[str] = None
    r"""Status message"""

    provider: Optional[str] = None
    r"""Provider name"""

    status: Optional[str] = None
    r"""Operation status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["message", "provider", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
