"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteToolCredentialsRequestTypedDict(TypedDict):
    tool_type: str
    r"""Tool category type (web_search, multimodal_analyzer)"""
    provider: str
    r"""Tool provider name (e.g., brave, gemini)"""


class DeleteToolCredentialsRequest(BaseModel):
    tool_type: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Tool category type (web_search, multimodal_analyzer)"""

    provider: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Tool provider name (e.g., brave, gemini)"""


class DeleteToolCredentialsResponseTypedDict(TypedDict):
    r"""Tool API key deleted successfully"""

    message: NotRequired[str]
    r"""Success message"""
    provider: NotRequired[str]
    r"""Tool provider name"""
    status: NotRequired[str]
    r"""Operation status (success)"""
    tool_type: NotRequired[str]
    r"""Tool category type"""


class DeleteToolCredentialsResponse(BaseModel):
    r"""Tool API key deleted successfully"""

    message: Optional[str] = None
    r"""Success message"""

    provider: Optional[str] = None
    r"""Tool provider name"""

    status: Optional[str] = None
    r"""Operation status (success)"""

    tool_type: Optional[str] = None
    r"""Tool category type"""
