"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InputJSONTypedDict(TypedDict):
    r"""Parsed tool input (optional)"""


class InputJSON(BaseModel):
    r"""Parsed tool input (optional)"""


class ExportToolCallTypedDict(TypedDict):
    r"""Complete tool call information for export"""

    finished: bool
    r"""Whether tool execution finished"""
    id: str
    r"""Tool call identifier"""
    input: str
    r"""Tool input as JSON string"""
    name: str
    r"""Tool name"""
    type: str
    r"""Tool type"""
    input_json: NotRequired[InputJSONTypedDict]
    r"""Parsed tool input (optional)"""
    result: NotRequired[str]
    r"""Tool execution result (optional)"""
    screenshot_urls: NotRequired[List[str]]
    r"""Screenshot URLs captured during tool execution (optional)"""


class ExportToolCall(BaseModel):
    r"""Complete tool call information for export"""

    finished: bool
    r"""Whether tool execution finished"""

    id: str
    r"""Tool call identifier"""

    input: str
    r"""Tool input as JSON string"""

    name: str
    r"""Tool name"""

    type: str
    r"""Tool type"""

    input_json: Annotated[Optional[InputJSON], pydantic.Field(alias="inputJson")] = None
    r"""Parsed tool input (optional)"""

    result: Optional[str] = None
    r"""Tool execution result (optional)"""

    screenshot_urls: Annotated[
        Optional[List[str]], pydantic.Field(alias="screenshotUrls")
    ] = None
    r"""Screenshot URLs captured during tool execution (optional)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["inputJson", "result", "screenshotUrls"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
