"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class FileInfoTypedDict(TypedDict):
    is_dir: bool
    r"""Whether this is a directory"""
    modified: int
    r"""Last modified timestamp (Unix time)"""
    name: str
    r"""File name"""
    size: int
    r"""File size in bytes"""


class FileInfo(BaseModel):
    is_dir: Annotated[bool, pydantic.Field(alias="isDir")]
    r"""Whether this is a directory"""

    modified: int
    r"""Last modified timestamp (Unix time)"""

    name: str
    r"""File name"""

    size: int
    r"""File size in bytes"""
