"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, Literal, Optional
from typing_extensions import NotRequired, TypedDict


GetAuthStatusAuthMethod = Literal[
    "oauth",
    "api_key",
    "none",
]
r"""Authentication method (oauth, api_key, none)"""


class GetAuthStatusProvidersTypedDict(TypedDict):
    auth_method: NotRequired[GetAuthStatusAuthMethod]
    r"""Authentication method (oauth, api_key, none)"""
    authenticated: NotRequired[bool]
    r"""Whether provider is authenticated"""
    display_name: NotRequired[str]
    r"""User-friendly provider name"""


class GetAuthStatusProviders(BaseModel):
    auth_method: Optional[GetAuthStatusAuthMethod] = None
    r"""Authentication method (oauth, api_key, none)"""

    authenticated: Optional[bool] = None
    r"""Whether provider is authenticated"""

    display_name: Optional[str] = None
    r"""User-friendly provider name"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_method", "authenticated", "display_name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAuthStatusResponseTypedDict(TypedDict):
    r"""Authentication status for all providers"""

    providers: NotRequired[Dict[str, GetAuthStatusProvidersTypedDict]]
    r"""Map of provider authentication status"""


class GetAuthStatusResponse(BaseModel):
    r"""Authentication status for all providers"""

    providers: Optional[Dict[str, GetAuthStatusProviders]] = None
    r"""Map of provider authentication status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["providers"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
