"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .userpreferencesresponse import (
    UserPreferencesResponse,
    UserPreferencesResponseTypedDict,
)
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class AvailableProvidersTypedDict(TypedDict):
    display_name: NotRequired[str]
    r"""User-friendly provider name"""
    models: NotRequired[List[str]]
    r"""Available models from this provider"""


class AvailableProviders(BaseModel):
    display_name: Optional[str] = None
    r"""User-friendly provider name"""

    models: Optional[List[str]] = None
    r"""Available models from this provider"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["display_name", "models"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetPreferencesResponseTypedDict(TypedDict):
    r"""User preferences and available providers"""

    available_providers: Dict[str, AvailableProvidersTypedDict]
    r"""Map of available AI providers and their models"""
    preferences: NotRequired[UserPreferencesResponseTypedDict]
    r"""User preferences configuration"""


class GetPreferencesResponse(BaseModel):
    r"""User preferences and available providers"""

    available_providers: Dict[str, AvailableProviders]
    r"""Map of available AI providers and their models"""

    preferences: Optional[UserPreferencesResponse] = None
    r"""User preferences configuration"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["preferences"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
