"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resterror import RESTError, RESTErrorTypedDict
from .sessiondata import SessionData, SessionDataTypedDict
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSessionRequestTypedDict(TypedDict):
    id: str
    r"""Session ID"""


class GetSessionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Session ID"""


class GetSessionResponseTypedDict(TypedDict):
    r"""Session details"""

    data: NotRequired[SessionDataTypedDict]
    error: NotRequired[RESTErrorTypedDict]
    message: NotRequired[str]
    r"""Optional message"""


class GetSessionResponse(BaseModel):
    r"""Session details"""

    data: Optional[SessionData] = None

    error: Optional[RESTError] = None

    message: Optional[str] = None
    r"""Optional message"""
