"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagedata import MessageData, MessageDataTypedDict
from .resterror import RESTError, RESTErrorTypedDict
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSessionMessagesRequestTypedDict(TypedDict):
    id: str
    r"""Session ID"""


class GetSessionMessagesRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Session ID"""


class GetSessionMessagesResponseTypedDict(TypedDict):
    r"""List of session messages"""

    data: NotRequired[List[MessageDataTypedDict]]
    error: NotRequired[RESTErrorTypedDict]
    message: NotRequired[str]
    r"""Optional message"""


class GetSessionMessagesResponse(BaseModel):
    r"""List of session messages"""

    data: Optional[List[MessageData]] = None

    error: Optional[RESTError] = None

    message: Optional[str] = None
    r"""Optional message"""
