"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSessionFileRequestTypedDict(TypedDict):
    id: str
    r"""Session ID"""
    filename: str
    r"""Filename to retrieve"""
    thumb: NotRequired[str]
    r"""Thumbnail specification: '100' (box), 'w100' (width), 'h100' (height)"""
    time: NotRequired[float]
    r"""Time offset in seconds for video thumbnails (default: 1.0)"""


class GetSessionFileRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Session ID"""

    filename: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Filename to retrieve"""

    thumb: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Thumbnail specification: '100' (box), 'w100' (width), 'h100' (height)"""

    time: Annotated[
        Optional[float],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Time offset in seconds for video thumbnails (default: 1.0)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["thumb", "time"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
