"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class GetSystemInfoResponseTypedDict(TypedDict):
    r"""System information"""

    storage_base_path: str
    r"""Absolute path to the storage base directory"""


class GetSystemInfoResponse(BaseModel):
    r"""System information"""

    storage_base_path: Annotated[str, pydantic.Field(alias="storageBasePath")]
    r"""Absolute path to the storage base directory"""
