"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class GetToolCredentialsStatusToolTypedDict(TypedDict):
    api_key_format: NotRequired[str]
    r"""Expected API key format"""
    api_key_required: NotRequired[bool]
    r"""Whether an API key is required"""
    authenticated: NotRequired[bool]
    r"""Whether the tool has valid credentials"""
    description: NotRequired[str]
    r"""Tool description"""
    display_name: NotRequired[str]
    r"""Tool display name"""
    provider: NotRequired[str]
    r"""Provider identifier"""


class GetToolCredentialsStatusTool(BaseModel):
    api_key_format: Optional[str] = None
    r"""Expected API key format"""

    api_key_required: Optional[bool] = None
    r"""Whether an API key is required"""

    authenticated: Optional[bool] = None
    r"""Whether the tool has valid credentials"""

    description: Optional[str] = None
    r"""Tool description"""

    display_name: Optional[str] = None
    r"""Tool display name"""

    provider: Optional[str] = None
    r"""Provider identifier"""


class GetToolCredentialsStatusCategoriesTypedDict(TypedDict):
    description: NotRequired[str]
    r"""Category description"""
    display_name: NotRequired[str]
    r"""Category display name"""
    icon: NotRequired[str]
    r"""Category icon"""
    tools: NotRequired[List[GetToolCredentialsStatusToolTypedDict]]
    r"""Tools in this category"""


class GetToolCredentialsStatusCategories(BaseModel):
    description: Optional[str] = None
    r"""Category description"""

    display_name: Optional[str] = None
    r"""Category display name"""

    icon: Optional[str] = None
    r"""Category icon"""

    tools: Optional[List[GetToolCredentialsStatusTool]] = None
    r"""Tools in this category"""


class GetToolCredentialsStatusResponseTypedDict(TypedDict):
    r"""Tool credentials status"""

    categories: NotRequired[Dict[str, GetToolCredentialsStatusCategoriesTypedDict]]
    r"""Tool categories grouped by type"""


class GetToolCredentialsStatusResponse(BaseModel):
    r"""Tool credentials status"""

    categories: Optional[Dict[str, GetToolCredentialsStatusCategories]] = None
    r"""Tool categories grouped by type"""
