"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GrantPermissionRequestTypedDict(TypedDict):
    id: str
    r"""Permission ID"""


class GrantPermissionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Permission ID"""


class GrantPermissionResponseTypedDict(TypedDict):
    r"""Permission grant status"""

    granted: NotRequired[bool]
    r"""Whether permission was granted"""


class GrantPermissionResponse(BaseModel):
    r"""Permission grant status"""

    granted: Optional[bool] = None
    r"""Whether permission was granted"""
