"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resterror import RESTError, RESTErrorTypedDict
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GrantPermissionRequestTypedDict(TypedDict):
    id: str
    r"""Permission ID"""


class GrantPermissionRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Permission ID"""


class GrantPermissionDataTypedDict(TypedDict):
    granted: NotRequired[bool]
    r"""Whether permission was granted"""


class GrantPermissionData(BaseModel):
    granted: Optional[bool] = None
    r"""Whether permission was granted"""


class GrantPermissionResponseTypedDict(TypedDict):
    r"""Permission grant status"""

    data: NotRequired[GrantPermissionDataTypedDict]
    error: NotRequired[RESTErrorTypedDict]
    message: NotRequired[str]
    r"""Optional message"""


class GrantPermissionResponse(BaseModel):
    r"""Permission grant status"""

    data: Optional[GrantPermissionData] = None

    error: Optional[RESTError] = None

    message: Optional[str] = None
    r"""Optional message"""
