"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HandleOAuthCallbackRequestTypedDict(TypedDict):
    code: str
    r"""Authorization code from OAuth provider"""
    provider: str
    r"""Provider name (anthropic)"""
    state: str
    r"""OAuth state for verification"""


class HandleOAuthCallbackRequest(BaseModel):
    code: str
    r"""Authorization code from OAuth provider"""

    provider: str
    r"""Provider name (anthropic)"""

    state: str
    r"""OAuth state for verification"""


class HandleOAuthCallbackResponseTypedDict(TypedDict):
    r"""OAuth completion status"""

    expires_in: NotRequired[int]
    r"""Seconds until token expiration"""
    message: NotRequired[str]
    r"""Status message"""
    provider: NotRequired[str]
    r"""Provider name"""
    status: NotRequired[str]
    r"""Operation status"""


class HandleOAuthCallbackResponse(BaseModel):
    r"""OAuth completion status"""

    expires_in: Optional[int] = None
    r"""Seconds until token expiration"""

    message: Optional[str] = None
    r"""Status message"""

    provider: Optional[str] = None
    r"""Provider name"""

    status: Optional[str] = None
    r"""Operation status"""
