"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resterror import RESTError, RESTErrorTypedDict
from mix_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HealthCheckDataTypedDict(TypedDict):
    status: NotRequired[str]
    r"""Health status"""
    timestamp: NotRequired[str]
    r"""Current timestamp"""
    version: NotRequired[str]
    r"""Application version"""


class HealthCheckData(BaseModel):
    status: Optional[str] = None
    r"""Health status"""

    timestamp: Optional[str] = None
    r"""Current timestamp"""

    version: Optional[str] = None
    r"""Application version"""


class HealthCheckResponseTypedDict(TypedDict):
    r"""Health information"""

    data: NotRequired[HealthCheckDataTypedDict]
    error: NotRequired[RESTErrorTypedDict]
    message: NotRequired[str]
    r"""Optional message"""


class HealthCheckResponse(BaseModel):
    r"""Health information"""

    data: Optional[HealthCheckData] = None

    error: Optional[RESTError] = None

    message: Optional[str] = None
    r"""Optional message"""
