"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HealthCheckResponseTypedDict(TypedDict):
    r"""Health information"""

    status: NotRequired[str]
    r"""Health status"""
    timestamp: NotRequired[str]
    r"""Current timestamp"""
    version: NotRequired[str]
    r"""Application version"""


class HealthCheckResponse(BaseModel):
    r"""Health information"""

    status: Optional[str] = None
    r"""Health status"""

    timestamp: Optional[str] = None
    r"""Current timestamp"""

    version: Optional[str] = None
    r"""Application version"""
