"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class HealthCheckResponseTypedDict(TypedDict):
    r"""Health information"""

    status: NotRequired[str]
    r"""Health status"""
    timestamp: NotRequired[str]
    r"""Current timestamp"""
    version: NotRequired[str]
    r"""Application version"""


class HealthCheckResponse(BaseModel):
    r"""Health information"""

    status: Optional[str] = None
    r"""Health status"""

    timestamp: Optional[str] = None
    r"""Current timestamp"""

    version: Optional[str] = None
    r"""Application version"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "timestamp", "version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
