"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class InitiateOAuthLoginResponseTypedDict(TypedDict):
    r"""Authentication URL"""

    auth_url: NotRequired[str]
    r"""OAuth authorization URL"""


class InitiateOAuthLoginResponse(BaseModel):
    r"""Authentication URL"""

    auth_url: Annotated[Optional[str], pydantic.Field(alias="authUrl")] = None
    r"""OAuth authorization URL"""
