"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ListCommandsResponseTypedDict(TypedDict):
    description: NotRequired[str]
    r"""Command description"""
    name: NotRequired[str]
    r"""Command name"""


class ListCommandsResponse(BaseModel):
    description: Optional[str] = None
    r"""Command description"""

    name: Optional[str] = None
    r"""Command name"""
