"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List
from typing_extensions import NotRequired, TypedDict


class ListMcpServersToolTypedDict(TypedDict):
    description: str
    r"""Tool description"""
    name: str
    r"""Tool name"""


class ListMcpServersTool(BaseModel):
    description: str
    r"""Tool description"""

    name: str
    r"""Tool name"""


class ListMcpServersResponseTypedDict(TypedDict):
    connected: bool
    r"""Whether the MCP server is currently connected"""
    name: str
    r"""MCP server name"""
    status: str
    r"""Server connection status (e.g., 'connected', 'failed', 'disconnected')"""
    tools: NotRequired[Nullable[List[ListMcpServersToolTypedDict]]]
    r"""List of tools provided by this MCP server (null if server is not connected)"""


class ListMcpServersResponse(BaseModel):
    connected: bool
    r"""Whether the MCP server is currently connected"""

    name: str
    r"""MCP server name"""

    status: str
    r"""Server connection status (e.g., 'connected', 'failed', 'disconnected')"""

    tools: OptionalNullable[List[ListMcpServersTool]] = UNSET
    r"""List of tools provided by this MCP server (null if server is not connected)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tools"])
        nullable_fields = set(["tools"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
