"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .resterror import RESTError, RESTErrorTypedDict
from mix_python_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ListCommandsDataTypedDict(TypedDict):
    description: NotRequired[str]
    r"""Command description"""
    name: NotRequired[str]
    r"""Command name"""


class ListCommandsData(BaseModel):
    description: Optional[str] = None
    r"""Command description"""

    name: Optional[str] = None
    r"""Command name"""


class ListCommandsResponseTypedDict(TypedDict):
    r"""List of commands"""

    data: NotRequired[List[ListCommandsDataTypedDict]]
    error: NotRequired[RESTErrorTypedDict]
    message: NotRequired[str]
    r"""Optional message"""


class ListCommandsResponse(BaseModel):
    r"""List of commands"""

    data: Optional[List[ListCommandsData]] = None

    error: Optional[RESTError] = None

    message: Optional[str] = None
    r"""Optional message"""
