"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListSessionsRequestTypedDict(TypedDict):
    include_subagents: NotRequired[bool]
    r"""Include subagent sessions in response (default: false, subagent sessions are hidden)"""


class ListSessionsRequest(BaseModel):
    include_subagents: Annotated[
        Optional[bool],
        pydantic.Field(alias="includeSubagents"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Include subagent sessions in response (default: false, subagent sessions are hidden)"""
