"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ResetPreferencesResponseTypedDict(TypedDict):
    r"""Reset preferences"""

    created_at: NotRequired[int]
    r"""Creation timestamp"""
    main_agent_max_tokens: NotRequired[int]
    r"""Reset main agent max tokens"""
    main_agent_model: NotRequired[str]
    r"""Reset main agent model"""
    main_agent_reasoning_effort: NotRequired[str]
    r"""Reset main agent reasoning effort"""
    preferred_provider: NotRequired[str]
    r"""Reset preferred provider"""
    sub_agent_max_tokens: NotRequired[int]
    r"""Reset sub agent max tokens"""
    sub_agent_model: NotRequired[str]
    r"""Reset sub agent model"""
    sub_agent_reasoning_effort: NotRequired[str]
    r"""Reset sub agent reasoning effort"""
    updated_at: NotRequired[int]
    r"""Reset timestamp"""


class ResetPreferencesResponse(BaseModel):
    r"""Reset preferences"""

    created_at: Optional[int] = None
    r"""Creation timestamp"""

    main_agent_max_tokens: Optional[int] = None
    r"""Reset main agent max tokens"""

    main_agent_model: Optional[str] = None
    r"""Reset main agent model"""

    main_agent_reasoning_effort: Optional[str] = None
    r"""Reset main agent reasoning effort"""

    preferred_provider: Optional[str] = None
    r"""Reset preferred provider"""

    sub_agent_max_tokens: Optional[int] = None
    r"""Reset sub agent max tokens"""

    sub_agent_model: Optional[str] = None
    r"""Reset sub agent model"""

    sub_agent_reasoning_effort: Optional[str] = None
    r"""Reset sub agent reasoning effort"""

    updated_at: Optional[int] = None
    r"""Reset timestamp"""
