"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


RespondToNotificationType = Literal[
    "acknowledge",
    "text",
    "choice",
]
r"""Response type"""


class RespondToNotificationRequestBodyTypedDict(TypedDict):
    type: RespondToNotificationType
    r"""Response type"""
    value: NotRequired[str]
    r"""User's text input or selected choice (optional for acknowledge type)"""


class RespondToNotificationRequestBody(BaseModel):
    type: RespondToNotificationType
    r"""Response type"""

    value: Optional[str] = None
    r"""User's text input or selected choice (optional for acknowledge type)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RespondToNotificationRequestTypedDict(TypedDict):
    id: str
    r"""Notification ID"""
    request_body: RespondToNotificationRequestBodyTypedDict


class RespondToNotificationRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Notification ID"""

    request_body: Annotated[
        RespondToNotificationRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
