"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


RESTErrorType = Literal[
    "bad_request",
    "not_found",
    "internal_error",
    "unauthorized",
    "validation_error",
]
r"""Error type"""


class RESTErrorTypedDict(TypedDict):
    code: int
    r"""HTTP status code"""
    message: str
    r"""Error message"""
    type: RESTErrorType
    r"""Error type"""


class RESTError(BaseModel):
    code: int
    r"""HTTP status code"""

    message: str
    r"""Error message"""

    type: RESTErrorType
    r"""Error type"""
