"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SetAPIKeyRequestTypedDict(TypedDict):
    api_key: str
    r"""API key for authentication"""


class SetAPIKeyRequest(BaseModel):
    api_key: Annotated[str, pydantic.Field(alias="apiKey")]
    r"""API key for authentication"""


class SetAPIKeyResponseTypedDict(TypedDict):
    r"""API key set status"""

    success: NotRequired[bool]
    r"""Whether API key was set successfully"""


class SetAPIKeyResponse(BaseModel):
    r"""API key set status"""

    success: Optional[bool] = None
    r"""Whether API key was set successfully"""
