"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel, UNSET_SENTINEL
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StartOAuthFlowRequestTypedDict(TypedDict):
    provider: str
    r"""Provider name (currently only 'anthropic')"""


class StartOAuthFlowRequest(BaseModel):
    provider: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Provider name (currently only 'anthropic')"""


class StartOAuthFlowResponseTypedDict(TypedDict):
    r"""OAuth authorization information"""

    auth_url: NotRequired[str]
    r"""OAuth authorization URL to redirect to"""
    message: NotRequired[str]
    r"""Instructions for completing OAuth flow"""
    state: NotRequired[str]
    r"""OAuth state token for verification"""


class StartOAuthFlowResponse(BaseModel):
    r"""OAuth authorization information"""

    auth_url: Optional[str] = None
    r"""OAuth authorization URL to redirect to"""

    message: Optional[str] = None
    r"""Instructions for completing OAuth flow"""

    state: Optional[str] = None
    r"""OAuth state token for verification"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth_url", "message", "state"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
