"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StartOAuthFlowRequestTypedDict(TypedDict):
    provider: str
    r"""Provider name (currently only 'anthropic')"""


class StartOAuthFlowRequest(BaseModel):
    provider: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Provider name (currently only 'anthropic')"""


class StartOAuthFlowResponseTypedDict(TypedDict):
    r"""OAuth authorization information"""

    auth_url: NotRequired[str]
    r"""OAuth authorization URL to redirect to"""
    message: NotRequired[str]
    r"""Instructions for completing OAuth flow"""
    state: NotRequired[str]
    r"""OAuth state token for verification"""


class StartOAuthFlowResponse(BaseModel):
    r"""OAuth authorization information"""

    auth_url: Optional[str] = None
    r"""OAuth authorization URL to redirect to"""

    message: Optional[str] = None
    r"""Instructions for completing OAuth flow"""

    state: Optional[str] = None
    r"""OAuth state token for verification"""
