"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
import pydantic
from typing import Literal
from typing_extensions import Annotated, TypedDict


Status = Literal["broadcasted",]
r"""Broadcast status"""


class StreamMessageResponseTypedDict(TypedDict):
    r"""Response from streaming message endpoint indicating broadcast status"""

    session_id: str
    r"""Session identifier"""
    status: Status
    r"""Broadcast status"""


class StreamMessageResponse(BaseModel):
    r"""Response from streaming message endpoint indicating broadcast status"""

    session_id: Annotated[str, pydantic.Field(alias="sessionId")]
    r"""Session identifier"""

    status: Status
    r"""Broadcast status"""
