"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ToolCallDataTypedDict(TypedDict):
    finished: bool
    r"""Whether tool call has finished"""
    id: str
    r"""Unique tool call identifier"""
    input: str
    r"""Tool input parameters"""
    name: str
    r"""Tool name"""
    type: str
    r"""Tool type"""
    is_error: NotRequired[bool]
    r"""Whether tool call resulted in error (optional)"""
    result: NotRequired[str]
    r"""Tool execution result (optional)"""


class ToolCallData(BaseModel):
    finished: bool
    r"""Whether tool call has finished"""

    id: str
    r"""Unique tool call identifier"""

    input: str
    r"""Tool input parameters"""

    name: str
    r"""Tool name"""

    type: str
    r"""Tool type"""

    is_error: Annotated[Optional[bool], pydantic.Field(alias="isError")] = None
    r"""Whether tool call resulted in error (optional)"""

    result: Optional[str] = None
    r"""Tool execution result (optional)"""
