"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .coretoolname import CoreToolName
from typing import Union
from typing_extensions import TypeAliasType


ToolNameTypedDict = TypeAliasType("ToolNameTypedDict", Union[CoreToolName, str])
r"""Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern"""


ToolName = TypeAliasType("ToolName", Union[CoreToolName, str])
r"""Tool name - either a core tool or MCP tool following {serverName}_{toolName} pattern"""
