"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .callback import Callback, CallbackTypedDict
from mix_python_sdk.types import BaseModel
from mix_python_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import List
from typing_extensions import Annotated, TypedDict


class UpdateSessionCallbacksRequestBodyTypedDict(TypedDict):
    callbacks: List[CallbackTypedDict]
    r"""Session-level callbacks that execute after tool completion. Environment variables available: CALLBACK_TOOL_RESULT, CALLBACK_TOOL_NAME, CALLBACK_TOOL_ID, CALLBACK_SESSION_ID"""


class UpdateSessionCallbacksRequestBody(BaseModel):
    callbacks: List[Callback]
    r"""Session-level callbacks that execute after tool completion. Environment variables available: CALLBACK_TOOL_RESULT, CALLBACK_TOOL_NAME, CALLBACK_TOOL_ID, CALLBACK_SESSION_ID"""


class UpdateSessionCallbacksRequestTypedDict(TypedDict):
    id: str
    r"""Session ID to update"""
    request_body: UpdateSessionCallbacksRequestBodyTypedDict


class UpdateSessionCallbacksRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Session ID to update"""

    request_body: Annotated[
        UpdateSessionCallbacksRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
