"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from mix_python_sdk.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


ValidatePreferredProviderAuthMethod = Literal[
    "oauth",
    "api_key",
    "none",
]
r"""Authentication method used"""


class ValidatePreferredProviderResponseTypedDict(TypedDict):
    r"""Preferred provider validation status"""

    auth_method: NotRequired[ValidatePreferredProviderAuthMethod]
    r"""Authentication method used"""
    message: NotRequired[str]
    r"""Status message"""
    provider: NotRequired[str]
    r"""Preferred provider name"""
    valid: NotRequired[bool]
    r"""Whether preferred provider is authenticated"""


class ValidatePreferredProviderResponse(BaseModel):
    r"""Preferred provider validation status"""

    auth_method: Optional[ValidatePreferredProviderAuthMethod] = None
    r"""Authentication method used"""

    message: Optional[str] = None
    r"""Status message"""

    provider: Optional[str] = None
    r"""Preferred provider name"""

    valid: Optional[bool] = None
    r"""Whether preferred provider is authenticated"""
