"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "mix-python-sdk"
__version__: str = "0.4.5"
__openapi_doc_version__: str = "1.0.0"
__gen_version__: str = "2.716.1"
__user_agent__: str = "speakeasy-sdk/python 0.4.5 2.716.1 1.0.0 mix-python-sdk"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
