name: Publish Package to PyPI

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy pylint uv
      - name: Lint with pylint
        run: |
          pylint --rcfile=pylintrc src/
      - name: Type check with mypy
        run: |
          mypy src/

  publish-pypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Build and publish
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_TOKEN }}
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}