name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv pylint mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    - name: Lint with pylint
      run: |
        # Use appropriate linting configuration if available
        pylint src/ || true
    - name: Type check with mypy
      run: |
        mypy src/ || true

  publish-pypi:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build uv
    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        # Remove 'v' prefix if present
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Using version $VERSION from release tag"
    - name: Update version in files
      run: |
        # Update pyproject.toml
        sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$VERSION\"/" pyproject.toml
        # Update version file if it exists
        if [ -f "src/mix_python_sdk/_version.py" ]; then
          sed -i "s/__version__: str = \"[0-9]*\.[0-9]*\.[0-9]*\"/__version__: str = \"$VERSION\"/" src/mix_python_sdk/_version.py
          sed -i "s/__user_agent__: str = \"speakeasy-sdk\/python [0-9]*\.[0-9]*\.[0-9]* /__user_agent__: str = \"speakeasy-sdk\/python $VERSION /" src/mix_python_sdk/_version.py
        fi
    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build
        
    - name: Publish package using OIDC
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true