name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy pylint pytest uv
        pip install -e .
    - name: Lint with pylint
      run: |
        pylint --rcfile=pylintrc src/
    - name: Type check with mypy
      run: |
        mypy src/
    # Uncomment the following step if you have tests
    # - name: Test with pytest
    #   run: |
    #     pytest